// UI 元素引用集中管理
export function getUiRefs() {
  const byId = (id) => document.getElementById(id);

  return {
    statusEl: byId('wtl-status'),
    pageMainEl: byId('wtl-page-main'),
    pageConfigEl: byId('wtl-page-config'),
    openConfigBtn: byId('wtl-open-config'),
    backMainBtn: byId('wtl-back-main'),
    batchBtn: byId('wtl-batch'),
    batchStartEl: byId('wtl-batch-start'),
    batchEndEl: byId('wtl-batch-end'),
    batchStepEl: byId('wtl-batch-step'),

    autoToggleBtn: byId('wtl-auto-toggle'),
    autoFloorsEl: byId('wtl-auto-floors'),
    autoEveryEl: byId('wtl-auto-every'),

    editTableBtn: byId('wtl-edit-table'),
    editTemplateBtn: byId('wtl-edit-template'),
    resetGlobalBtn: byId('wtl-reset-global'),
    clearTableBtn: byId('wtl-clear-table'),
    historyBackBtn: byId('wtl-history-back'),
    historyUndoBtn: byId('wtl-history-undo'),
    historyBtn: byId('wtl-history'),
    editPrepromptBtn: byId('wtl-edit-preprompt'),
    resetPrepromptBtn: byId('wtl-reset-preprompt'),
    editInstructionBtn: byId('wtl-edit-instruction'),
    resetInstructionBtn: byId('wtl-reset-instruction'),
    refreshSchemaBtn: byId('wtl-refresh-schema'),
    resetSchemaBtn: byId('wtl-reset-schema'),
    editSchemaBtn: byId('wtl-edit-schema'),
    templateEditorEl: byId('wtl-template-editor'),

    prepromptPresetEl: byId('wtl-preprompt-preset'),
    prepromptPresetNameEl: byId('wtl-preprompt-preset-name'),
    prepromptPresetLoadEl: byId('wtl-preprompt-preset-load'),
    prepromptPresetSaveEl: byId('wtl-preprompt-preset-save'),
    prepromptPresetRenameEl: byId('wtl-preprompt-preset-rename'),
    prepromptPresetDelEl: byId('wtl-preprompt-preset-del'),
    prepromptPresetImportEl: byId('wtl-preprompt-preset-import'),
    prepromptPresetExportEl: byId('wtl-preprompt-preset-export'),
    prepromptPresetFileEl: byId('wtl-preprompt-preset-file'),

    instructionPresetEl: byId('wtl-instruction-preset'),
    instructionPresetNameEl: byId('wtl-instruction-preset-name'),
    instructionPresetLoadEl: byId('wtl-instruction-preset-load'),
    instructionPresetSaveEl: byId('wtl-instruction-preset-save'),
    instructionPresetRenameEl: byId('wtl-instruction-preset-rename'),
    instructionPresetDelEl: byId('wtl-instruction-preset-del'),
    instructionPresetImportEl: byId('wtl-instruction-preset-import'),
    instructionPresetExportEl: byId('wtl-instruction-preset-export'),
    instructionPresetFileEl: byId('wtl-instruction-preset-file'),

    sectionListEl: byId('wtl-section-list'),
    columnListEl: byId('wtl-column-list'),
    sectionAddBtn: byId('wtl-section-add'),
    sectionApplyBtn: byId('wtl-section-apply'),
    columnAddBtn: byId('wtl-column-add'),
    editorOverlayEl: byId('wtl-editor-overlay'),
    editorDialogTitleEl: byId('wtl-editor-dialog-title'),
    editorDialogNameEl: byId('wtl-editor-dialog-name'),
    editorDialogDefEl: byId('wtl-editor-dialog-definition'),
    editorDialogDelEl: byId('wtl-editor-dialog-delete'),
    editorDialogAddEl: byId('wtl-editor-dialog-insert'),
    editorDialogEditEl: byId('wtl-editor-dialog-update'),
    editorDialogFillEl: byId('wtl-editor-dialog-fill'),
    editorDialogFillRowEl: byId('wtl-editor-dialog-fill-row'),
    editorDialogSendEl: byId('wtl-editor-dialog-send'),
    editorDialogSendRowEl: byId('wtl-editor-dialog-send-row'),
    editorDialogInsertRowEl: byId('wtl-editor-dialog-insert-row'),
    editorDialogUpdateRowEl: byId('wtl-editor-dialog-update-row'),
    editorDialogDeleteRowEl: byId('wtl-editor-dialog-delete-row'),
    editorDialogInsertToggleEl: byId('wtl-editor-dialog-insert-toggle'),
    editorDialogUpdateToggleEl: byId('wtl-editor-dialog-update-toggle'),
    editorDialogDeleteToggleEl: byId('wtl-editor-dialog-delete-toggle'),
    editorDialogInsertEnabledEl: byId('wtl-editor-dialog-insert-enabled'),
    editorDialogUpdateEnabledEl: byId('wtl-editor-dialog-update-enabled'),
    editorDialogDeleteEnabledEl: byId('wtl-editor-dialog-delete-enabled'),
    editorDialogSaveEl: byId('wtl-editor-dialog-save'),
    editorDialogCloseEl: byId('wtl-editor-dialog-close'),

    modalEl: byId('wtl-modal'),
    modalTitleEl: byId('wtl-modal-title'),
    modalContentEl: byId('wtl-modal-content'),
    modalCustomEl: byId('wtl-modal-custom'),
    modalActionsEl: byId('wtl-modal-actions'),
    modalCloseEl: byId('wtl-modal-close'),

    tableMdEl: byId('wtl-table-md'),
    schemaModeEl: byId('wtl-schema-mode'),
    schemaEl: byId('wtl-schema'),
    schemaPresetEl: byId('wtl-schema-preset'),
    schemaPresetNameEl: byId('wtl-schema-preset-name'),
    schemaPresetLoadEl: byId('wtl-schema-preset-load'),
    schemaPresetSaveEl: byId('wtl-schema-preset-save'),
    schemaPresetRenameEl: byId('wtl-schema-preset-rename'),
    schemaPresetDelEl: byId('wtl-schema-preset-del'),
    schemaPresetImportEl: byId('wtl-schema-preset-import'),
    schemaPresetExportEl: byId('wtl-schema-preset-export'),
    schemaPresetFileEl: byId('wtl-schema-preset-file'),
    schemaBindGlobalEl: byId('wtl-schema-bind-global'),
    schemaBindCharacterEl: byId('wtl-schema-bind-character'),
    schemaBindChatEl: byId('wtl-schema-bind-chat'),
    schemaBindCharacterNameEl: byId('wtl-schema-bind-character-name'),
    schemaBindChatNameEl: byId('wtl-schema-bind-chat-name'),
    schemaEffectiveEl: byId('wtl-schema-effective'),

    headEl: byId('wtl-preview-head'),
    bodyEl: byId('wtl-preview-body'),
    tableTabsEl: byId('wtl-table-tabs'),
    blockListEl: byId('wtl-block-list'),
    refBlockListEl: byId('wtl-ref-block-list'),
    blockAddEl: byId('wtl-block-add'),
    refBlockAddEl: byId('wtl-ref-block-add'),
    blockResetEl: byId('wtl-block-reset'),
    refBlockResetEl: byId('wtl-ref-block-reset'),

    wbModeEl: byId('wtl-wb-mode'),
    wbManualWrapEl: byId('wtl-wb-manual-wrap'),
    wbManualEl: byId('wtl-wb-manual'),
    wbManualUiEl: byId('wtl-wb-manual-ui'),
    wbManualRefreshEl: byId('wtl-wb-manual-refresh'),
    entryEl: byId('wtl-entry'),
    prePromptEl: byId('wtl-preprompt'),
    instructionEl: byId('wtl-instruction'),
    sendModeEl: byId('wtl-send-mode'),
    externalEl: byId('wtl-mode-external'),
    stModeEl: byId('wtl-mode-st'),
    instBlockEl: byId('wtl-inst-block'),
    schemaBlockEl: byId('wtl-schema-block'),
    tablePreviewEl: byId('wtl-table-preview'),
    logContentEl: byId('wtl-log-content'),
    logPromptBtn: byId('wtl-log-prompt'),
    logAiBtn: byId('wtl-log-ai'),
    logRefreshBtn: byId('wtl-log-refresh'),

    externalNavOrderBtn: byId('wtl-external-nav-order'),
    externalNavRefBtn: byId('wtl-external-nav-ref'),
    externalNavWbBtn: byId('wtl-external-nav-wb'),
    externalPanelOrderEl: byId('wtl-external-panel-order'),
    externalPanelRefEl: byId('wtl-external-panel-ref'),
    externalPanelWbEl: byId('wtl-external-panel-wb'),

    openaiPresetEl: byId('wtl-openai-preset'),
    openaiPresetNameEl: byId('wtl-openai-preset-name'),
    openaiPresetLoadEl: byId('wtl-openai-preset-load'),
    openaiPresetDelEl: byId('wtl-openai-preset-del'),

    openaiUrlEl: byId('wtl-openai-url'),
    openaiKeyEl: byId('wtl-openai-key'),
    openaiModelEl: byId('wtl-openai-model'),
    openaiRefreshEl: byId('wtl-openai-refresh'),
    openaiTempEl: byId('wtl-openai-temp'),
    openaiMaxEl: byId('wtl-openai-max'),
    externalSaveEl: byId('wtl-external-save'),

    tablePosEl: byId('wtl-table-pos'),
    tableRoleEl: byId('wtl-table-role'),
    tableDepthEl: byId('wtl-table-depth'),
    tableOrderEl: byId('wtl-table-order'),
    tableInjectToggleBtn: byId('wtl-table-inject-toggle'),

    instPosEl: byId('wtl-inst-pos'),
    instRoleEl: byId('wtl-inst-role'),
    instDepthEl: byId('wtl-inst-depth'),
    instOrderEl: byId('wtl-inst-order'),
    instInjectToggleEl: byId('wtl-inst-inject-toggle'),

    schemaPosEl: byId('wtl-schema-pos'),
    schemaRoleEl: byId('wtl-schema-role'),
    schemaDepthEl: byId('wtl-schema-depth'),
    schemaOrderEl: byId('wtl-schema-order'),
    schemaInjectToggleEl: byId('wtl-schema-inject-toggle')
  };
}
